#!/bin/bash -l

#$ -P bf528
#$ -cwd
#$ -j y
#$ -pe mpi_16_tasks_per_node 16

#$ -S /bin/bash
module load python3 samtools rseqc
echo "Running job $JOB_ID"
echo "Started: $(date +%F)"
echo "Running in directory: $PWD"

geneBody_coverage.py -i P0_1_tophat/accepted_hits.bam -r /project/bf528/project_2/reference/annot/mm9.bed -o v1

# Files to be used are /projectnb/bf528/users/group6/project_2/samples/P0_1_1.fastq and P0_1_2.fastq
echo "Job finished: $(date +%F)"
